#!/bin/bash


USERID=$(id -u)

if [ $USERID -ne 0 ]
 then 
    echo "error:please run this script with root access"
      exit 1
  #else
    #echo "Info:you are root access" 
fi 

yum install mysqllll -y 
